# Generated by Django 2.2.13 on 2020-12-02 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20201130_1440'),
    ]

    operations = [
        migrations.CreateModel(
            name='Timer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('minute', models.FloatField(choices=[(0.5, 'Advanced'), (1, 'Normal'), (2, 'Easy')], default=1)),
            ],
        ),
    ]
