# Generated by Django 2.2.13 on 2020-12-02 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20201202_0329'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timer',
            name='minute',
            field=models.FloatField(choices=[(0.5, 'Advanced (0.5min)'), (1, 'Normal (1min)'), (2, 'Easy (2min)')], default=1, help_text='How Clever And Fast You Are?'),
        ),
    ]
