# Generated by Django 2.2.13 on 2020-12-02 13:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20201202_1647'),
    ]

    operations = [
        migrations.RenameField(
            model_name='timer',
            old_name='minute',
            new_name='difficulty',
        ),
    ]
