# Generated by Django 2.2.13 on 2020-12-03 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20201202_1649'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timer',
            name='difficulty',
            field=models.FloatField(choices=[(0.5, 'Advanced (30-sek)'), (1, 'Normal (1min)'), (2, 'Easy (2min)')], default=1, help_text='How Clever And Fast You Are?'),
        ),
    ]
